### ISSUE TITLE
Hey Bruno!

### ISSUE THREAD

**Issue by eurabilis** [rochacbruno/quokka_ng#1]
First I want to say I will still be following quokka, supporting it and using it for my sites! I am excited about the new version and I am glad by doing what you have to do, it will let you keep quokka, make it better and even keep your head more organized! With that said, I am trying to install the new version. I changed to using python3.6 on debian sid in my virtualenv 
`(quokkaenv) root » [quokka_ng]: python -V
Python 3.6.1rc1
(quokkaenv) root » [quokka_ng]:`

But when I went to install quokka, I would get errors. Tracing those errors myself I noticed I was simply missing things so I installed them one by one. Also I ran 
`git clone https://github.com/rochacbruno/quokka_ng.git` in my virtualenv, changed directory to quokka, and ran pip3 install --upgrade -r requirements.txt. It grabbed a bunch of things, and installed them, just like the old version. But when I run pip3 install quokka I would still get errors. I traced them, found some more packages I needed, as a matter of fact one was flask_htmlbuilder, but the actual package I found i needed was QUOKKA-flask-htmlbuilder! So I went thru and installed some more things and finally I am stuck here I will attach the log below.

`(quokkaenv) root » [quokka_ng]: pip3 install quokka
Collecting quokka
  Using cached quokka-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    /tmp/pip-build-jla_rh9x/quokka/quokka/core/admin/__init__.py:7: ExtDeprecationWarning: Importing flask.ext.admin is deprecated, use flask_admin instead.
      from flask.ext.admin import Admin
    /tmp/pip-build-jla_rh9x/quokka/quokka/core/db.py:4: ExtDeprecationWarning: Importing flask.ext.mongoengine is deprecated, use flask_mongoengine instead.
      from flask.ext.mongoengine import MongoEngine
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-jla_rh9x/quokka/setup.py", line 6, in <module>
        import quokka
      File "/tmp/pip-build-jla_rh9x/quokka/quokka/__init__.py", line 15, in <module>
        from .core.admin import create_admin
      File "/tmp/pip-build-jla_rh9x/quokka/quokka/core/admin/__init__.py", line 9, in <module>
        from ..models import (Link, Config, SubContentPurpose, ChannelType,
      File "/tmp/pip-build-jla_rh9x/quokka/quokka/core/models.py", line 10, in <module>
        from quokka.core.db import db
      File "/tmp/pip-build-jla_rh9x/quokka/quokka/core/db.py", line 4, in <module>
        from flask.ext.mongoengine import MongoEngine
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 646, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 616, in _load_backward_compatible
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/flask/exthook.py", line 77, in load_module
        __import__(realname)
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/flask_mongoengine/__init__.py", line 6, in <module>
        import mongoengine
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/__init__.py", line 3, in <module>
        from mongoengine import document
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/document.py", line 10, in <module>
        from mongoengine.base import (BaseDict, BaseDocument, BaseList,
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/base/__init__.py", line 9, in <module>
        from mongoengine.base.document import *
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/base/document.py", line 17, in <module>
        from mongoengine.base.fields import ComplexBaseField
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/base/fields.py", line 462, in <module>
        class GeoJsonBaseField(BaseField):
      File "/usr/home/quokkaenv/lib/python3.6/site-packages/mongoengine/base/fields.py", line 468, in GeoJsonBaseField
        _geo_index = pymongo.GEOSPHERE
    AttributeError: module 'pymongo' has no attribute 'GEOSPHERE'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-jla_rh9x/quokka/
(quokkaenv) root » [quokka_ng]:`

Thank you very much for your help, and once I get a basic stable site up, I would love to spend some time writing documentation and howtos for quokka! I have plenty of free time available so please let me know. I have three test machines of varying hardware from older to latest I can test on, with windows 10, arch linux, and debian sid available. I just need guidance on what needs to be done.

**Comment by rochacbruno** [comment]
> NOTE: It is in very early stage, **wait** some days until I get other modules ported to the new version!!!


Hi @eurabilis for now you can do:

```bash
# activate new virtualenv with Python 3.6
$ git clone https://github.com/rochacbruno/quokka_ng.git
$ cd quokka_ng
$ python setup.py develop
$ pip3 install -r requirements.txt 
```

That would give you a development branch with some working feature.

```bash
$ cd my_projects  # the folder where you keep your projects
$ quokka init 'My Website'
Generating your website in my_website folder
$ cd my_website
$ ls
themes/ databases/ manage.yml settings.yml
```

Most of the folders are still empty because the development is in the very beginning.

```bash
$ quokka --help
```


```bash
$ quokka adduser --username=admin --email=you@server.com --password=1234
User admin created! ...

# quokka runserver
running...
```

go to http://localhost:5000/admin and you should be able to login and play a bit with experimental admin.

> NOTE: It is in very early stage, **wait** some days until I get other modules ported to the new version!!!

# important!!!

- All your suggestions are very welcome
- All your help very welcome
- I'll provide a migration script for those running old version (I may use myself to migrate my brunorocha.org blog)

**Comment by eurabilis** [comment]
Great thanks! Ill go ahead and wait a week or so. If you need anything ask!

**Comment by CptJason** [comment]
python setup.py develop
error in quokka setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Invalid requirement, parse error at "'+https:/'"

**Comment by tiagocordeiro** [comment]
same issue here

```
$ python setup.py develop
error in quokka setup command: 'install_requires' must be a string or list
of strings containing valid project/version requirement specifiers; Invalid
requirement, parse error at "'+https:/'"
```

```
$ pip freeze
awesome-slugify==1.6.5
Babel==2.4.0
blinker==1.4
click==6.7
colorama==0.3.9
decorator==4.0.11
dynaconf==0.4.5
Flask==0.12.1
Flask-Admin==1.5.0
Flask-BabelEx==0.9.3
Flask-Gravatar==0.4.2
Flask-Login==0.3.2
Flask-Mail==0.9.1
Flask-Mistune==0.1.1
Flask-OAuthlib==0.9.3
Flask-Principal==0.4.0
Flask-Security==1.7.5
Flask-WTF==0.14.2
Frozen-Flask==0.14
import-string==0.1.0
infinity==1.4
intervals==0.8.0
itsdangerous==0.24
Jinja2==2.9.6
manage==0.1.13
MarkupSafe==1.0
mistune==0.7.4
oauthlib==2.0.2
olefile==0.44
passlib==1.7.1
Pillow==4.1.1
py==1.4.33
pymongo==2.4.1
PyRSS2Gen==1.1
pytest==3.0.7
pytz==2017.2
PyYAML==3.12
quokka-flask-htmlbuilder==0.13
Quokka-Themes==0.1.4
regex==2017.4.29
requests==2.14.2
requests-oauthlib==0.8.0
simplejson==3.10.0
six==1.10.0
speaklater==1.3
tablib==0.11.4
tinydb==3.2.3
tinydb-serialization==1.0.4
tinymongo==0.1.9.dev0
Unidecode==0.4.20
update==0.4.4
validators==0.11.3
Werkzeug==0.12.1
WTForms==2.1
WTForms-Components==0.10.3

```

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 22 2016, 17:23:13)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
```

```
OS: 64bit Mac OS X 10.12.4 16E195
Kernel: x86_64 Darwin 16.5.0
```

**Comment by diegoponciano** [comment]
Installing from github won't work with `install_requires`, we have to add those dependencies to `dependency_links` instead.

**Comment by graham2** [comment]
Just wondering what the status is and is there likely to be much change in the near future ?
I was interested in the old Quokka but never used it but now do want to start using it...and I could probably contribute - what's the plan for that ?

graham

**Comment by rochacbruno** [comment]
hi @graham2 I am working on this new version, but as I have other projects this is not my main priority, I have a deadline in mind which is October (because I have a project to launch using Quokka).

I am open for contributions

**Comment by jeffgodwyll** [comment]
hi @rochacbruno is there a public roadmap of some sorts that can guide potential contributions? Or anywhere to start? I'm looking to devote some of my time to open source these coming weeks :)

**Comment by rochacbruno** [comment]
@eurabilis @jeffgodwyll @graham2 @diegoponciano @tiagocordeiro @CptJason 

https://github.com/rochacbruno/quokka_ng#setup-a-contributor-environment

**Comment by rochacbruno** [comment]
Closing this issue as already have all roadmap items opened as issues
